"""empty message

Revision ID: 2f8215174b
Revises: None
Create Date: 2014-05-06 10:43:07.129496

"""

# revision identifiers, used by Alembic.
revision = '2f8215174b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
