"""Added index to path column

Revision ID: 79ce509c8f
Revises: 2186695bff9
Create Date: 2014-05-12 19:52:06.879821

"""

# revision identifiers, used by Alembic.
revision = '79ce509c8f'
down_revision = '2186695bff9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_rasmusmediaweb_path_cache_path'), 'rasmusmediaweb_path_cache', ['path'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rasmusmediaweb_path_cache_path'), table_name='rasmusmediaweb_path_cache')
    ### end Alembic commands ###
